wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      4: 3.8.8
      5: 0.10.31
      8:
      - 3
      - 5
epoch:
  desc: null
  value: '10'
log_interval:
  desc: null
  value: 100
lr:
  desc: null
  value: '0.03'
model_version:
  desc: null
  value: 0
